<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Commerce.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\E-Commerce.Data\E-Commerce.Data.csproj" />
    <ProjectReference Include="..\E-Commerce.Infrustructure\E-Commerce.Infrustructure.csproj" />
    <ProjectReference Include="..\E-Commerce.Service\E-Commerce.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\Commands\Vaildations\" />
    <Folder Include="Features\Authentication\Queries\Handlers\" />
    <Folder Include="Features\Authentication\Queries\Models\" />
    <Folder Include="Features\Authentication\Queries\Response\" />
    <Folder Include="Features\Categorys\Commands\Vaildations\" />
    <Folder Include="Features\Companies\Commands\Vaildations\" />
    <Folder Include="Features\Companies\Queries\Handlers\" />
    <Folder Include="Features\Companies\Queries\Models\" />
    <Folder Include="Features\Companies\Queries\Response\" />
    <Folder Include="Features\Shipping\" />
    <Folder Include="Features\ProductImages\Commands\Vaildations\" />
    <Folder Include="Features\ProductImages\Queries\Handlers\" />
    <Folder Include="Features\ProductImages\Queries\Models\" />
    <Folder Include="Features\ProductImages\Queries\Response\" />
    <Folder Include="Features\ProductOptions\Commands\Vaildations\" />
    <Folder Include="Features\ProductOptions\Queries\Handlers\" />
    <Folder Include="Features\ProductOptions\Queries\Models\" />
    <Folder Include="Features\ProductOptions\Queries\Response\" />
    <Folder Include="Features\ProductOptionValues\Commands\Vaildations\" />
    <Folder Include="Features\ProductOptionValues\Queries\Handlers\" />
    <Folder Include="Features\ProductOptionValues\Queries\Models\" />
    <Folder Include="Features\ProductOptionValues\Queries\Response\" />
    <Folder Include="Features\ProductPriceTiers\Commands\Vaildations\" />
    <Folder Include="Features\ProductPriceTiers\Queries\Handlers\" />
    <Folder Include="Features\ProductPriceTiers\Queries\Models\" />
    <Folder Include="Features\ProductPriceTiers\Queries\Response\" />
    <Folder Include="Features\Products\Commands\Vaildations\" />
    <Folder Include="Features\ProductVariants\Commands\Vaildations\" />
    <Folder Include="Features\ProductVariants\Queries\Handlers\" />
    <Folder Include="Features\ProductVariants\Queries\Models\" />
    <Folder Include="Features\ProductVariants\Queries\Response\" />
    <Folder Include="Mapping\Companies\QueriesMapping\" />
    <Folder Include="Mapping\ProductImage\QueriesMapping\" />
    <Folder Include="Mapping\ProductOptions\QueriesMapping\" />
    <Folder Include="Mapping\ProductOptionValues\QueriesMapping\" />
    <Folder Include="Mapping\ProductPriceTiers\QueriesMapping\" />
    <Folder Include="Mapping\ProductVariant\Command\" />
    <Folder Include="Mapping\ProductVariant\Queries\" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
		<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.3" />
		<PackageReference Include="RavenDB.Client" Version="7.2.1" />
	</ItemGroup>

</Project>
